# Connexion à la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/job_db
spring.datasource.username=job_user
spring.datasource.password=***REMOVED***

# Configuration JPA
spring.jpa.hibernate.ddl-auto=update
# Afficher les requêtes SQL générées par Hibernate dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Configuration du dialecte PostgreSQL pour Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect